name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_lint_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        name: Publishing to NPM
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
