name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run lint
    - run: npm test
  generate_docs:
    needs: lint_test
    - name: Generating docs files
      if: github.ref == 'refs/heads/master'
      run: npm run docs
    - name: Committing docs files
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ github.ref }}
        git add website
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "CI: Automated docs push" -a | exit 0
    - name: Pushing docs changes to master
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  npm_publish:
    needs: lint_test
    - name: Publish to npm
      if: github.ref == 'refs/heads/master'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
